/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125608-g150f7d15df-20260714"
#endif /* AVUTIL_FFVERSION_H */
